# -*- coding: utf-8 -*-
"""Transcript Implementation Tool (Python)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAB_zq63E3tqw32ENU3qFEAGesOtmO5j
"""

import os
import json
import requests
import time

class TranscriptArchitect:
    """
    A sophisticated implementation engine that converts YouTube transcripts
    into high-granularity technical manuals using the Gemini API.
    """

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent"

        # The refined system prompt focused on high-granularity extraction
        self.system_prompt = (
            "You are a Senior Technical Implementation Engineer. Your task is to turn raw transcripts "
            "into a 'High-Granularity Deployment Manual'.\n\n"
            "CRITICAL INSTRUCTIONS:\n"
            "1. DO NOT be vague. Specify UI locations like 'Agent Manager' or 'Inbox'.\n"
            "2. EXTRACT COMMANDS: Capture terminal commands, CLI operations, and file names (e.g., brain.md).\n"
            "3. MAPPING: Mention exactly WHERE in the UI actions happen.\n"
            "4. INTEGRATIONS: Define API key locations and MCP server configuration steps.\n\n"
            "STRUCTURE:\n"
            "- EXECUTION GOAL\n"
            "- REQUIRED ASSETS (API Keys, Files, URLs)\n"
            "- THE SETUP (Click-by-Click)\n"
            "- THE BUILD (Workflow & Approvals)\n"
            "- SPECIFIC INTEGRATIONS (MCP, Firecrawl, GitHub)\n"
            "- USE CASE WALKTHROUGH"
        )

    def generate_guide(self, transcript_content: str, retries=5):
        """
        Calls Gemini API with exponential backoff for reliability.
        """
        payload = {
            "contents": [{"parts": [{"text": f"Here is the transcript/markdown source:\n\n{transcript_content}"}]}],
            "systemInstruction": {"parts": [{"text": self.system_prompt}]}
        }

        headers = {"Content-Type": "application/json"}
        params = {"key": self.api_key}

        for i in range(retries):
            try:
                response = requests.post(
                    self.base_url,
                    headers=headers,
                    params=params,
                    json=payload
                )
                response.raise_for_status()
                result = response.json()
                return result['candidates'][0]['content']['parts'][0]['text']
            except Exception as e:
                if i == retries - 1:
                    return f"Error after {retries} attempts: {str(e)}"
                wait_time = 2 ** i
                time.sleep(wait_time)

def main():
    # Setup - In a real product, use environment variables for API keys
    api_key = os.getenv("GEMINI_API_KEY", "")

    if not api_key:
        print("Please set the GEMINI_API_KEY environment variable.")
        return

    architect = TranscriptArchitect(api_key)

    # Example: Process a local markdown file
    # This allows for batch processing which HTML cannot do easily.
    input_file = "transcript.md"
    output_file = "implementation_guide.md"

    if os.path.exists(input_file):
        with open(input_file, "r", encoding="utf-8") as f:
            content = f.read()

        print(f"--- Processing: {input_file} ---")
        guide = architect.generate_guide(content)

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(guide)

        print(f"--- Success! Guide saved to: {output_file} ---")
    else:
        print(f"File {input_file} not found. Please place a markdown file in this directory.")

if __name__ == "__main__":
    main()